name: CI build application fro mac-os and windows

on: 
  push:
    branches:
      - Release

jobs:
  build_on_mac:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@Release
      with:
        ref: electron
    - uses: actions/setup-node@Release
      with:
        node-version: 10.x
    - name: see directory
      run: ls
  build_on_win:
    runs-on: windows-2016
    steps:
    - uses: actions/checkout@master
      with:
        ref: feature/github-actions        
    - uses: actions/setup-node@master
      with:
        node-version: 10.16
    - name: see directory
      run: ls
